# **Получение координат**

In [4]:
!wget -cq https://github.com/postlogist/ampl_examples/raw/main/geocoder/geocoder.py

In [5]:
import pandas as pd
from geocoder import geocode_df

In [7]:
!wget https://github.com/polina-jpg/pirelli_rs/raw/refs/heads/main/data/data_pirelli_geocode.xlsx

--2026-06-27 18:29:44--  https://github.com/polina-jpg/pirelli_rs/raw/refs/heads/main/data/data_pirelli_geocode.xlsx
Resolving github.com (github.com)... 140.82.112.3
Connecting to github.com (github.com)|140.82.112.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/polina-jpg/pirelli_rs/refs/heads/main/data/data_pirelli_geocode.xlsx [following]
--2026-06-27 18:29:44--  https://raw.githubusercontent.com/polina-jpg/pirelli_rs/refs/heads/main/data/data_pirelli_geocode.xlsx
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 34711 (34K) [application/octet-stream]
Saving to: ‘data_pirelli_geocode.xlsx’

data_pirelli_geocod 100%[===================>]  33.90K  --.-KB/s    in 0.005s

2026-06-27 18:29:44 (6.35 MB/s) - ‘data_pirelli_geocode.xlsx’ saved [34711/34711]

In [8]:
input_file = "data_pirelli_geocode.xlsx"

plants = pd.read_excel(input_file, sheet_name="plants")
warehouses = pd.read_excel(input_file, sheet_name="warehouses")
cities = pd.read_excel(input_file, sheet_name="cities")

print("plants:", plants.shape)
print("warehouses:", warehouses.shape)
print("cities:", cities.shape)

plants: (7, 4)
warehouses: (29, 4)
cities: (30, 3)

In [9]:
plants_locations = plants[["id", "city", "country"]].copy()
plants_locations["type"] = "plant"

warehouses_locations = warehouses[["id", "city", "country"]].copy()
warehouses_locations["type"] = "warehouse"

cities_locations = cities[["id", "city", "country"]].copy()
cities_locations["type"] = "city"

locations = pd.concat(
    [
        plants_locations,
        warehouses_locations,
        cities_locations,
    ],
    ignore_index=True
)

locations = locations[["type", "id", "city", "country"]]

print(f"Число строк: {len(locations)}")
locations.head()

Число строк: 66

    type  id              city  country
0  plant  P1          Carlisle       UK
1  plant  P2          Breuberg  Germany
2  plant  P3           Slatina  Romania
3  plant  P4  Settimo Torinese    Italy
4  plant  P5             Izmit   Turkey

In [ ]:
result = geocode_df(
    locations,
    address=None,
    city="city",
    region=None,
    country="country",
    user_agent="pirelli_emml_geocode",
    min_delay_seconds=1.1,
    max_retries=3,
    language="en",
)

Геокодирование:  82%|████████▏ | 54/66 [00:57<00:14,  1.18s/it]

In [ ]:
result

     type   id              city  country   latitude  longitude status
0   plant   P1          Carlisle       UK  54.894848  -2.936231     ok
1   plant   P2          Breuberg  Germany  49.823777   9.029779     ok
2   plant   P3           Slatina  Romania  44.429997  24.363184     ok
3   plant   P4  Settimo Torinese    Italy  45.137221   7.771253     ok
4   plant   P5             Izmit   Turkey  40.772114  29.950562     ok
..    ...  ...               ...      ...        ...        ...    ...
61   city  C26        Manchester       UK  53.442462  -2.232455     ok
62   city  C27        Birmingham       UK  52.494899  -1.851844     ok
63   city  C28            Naples    Italy  40.835885  14.248768     ok
64   city  C29           Cologne  Germany  50.938361   6.959974     ok
65   city  C30              Lyon   France  45.757814   4.832011     ok

[66 rows x 7 columns]

In [ ]:
output_file = "pirelli_data_coor.xlsx"

result.to_excel(output_file, index=False)

print(f"\nСохранено в {output_file}")

Сохранено в pirelli_data_coor.xlsx